---
pagetitle: "Resources"
toc: true
---

```{=html}
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="index.html">Home</a></li>
    <li class="breadcrumb-item active" aria-current="page">Resources</li>
  </ol>
</nav>
```

<#Writing great papers in high impact journals: An Introduction for Researchers (Alice Wood)

{{< pdf phdtcd.pdf width=600 height=400 image_width=600 image_border=1 image=firstslide.png >}}
>


## Datasets

 ***Data source and Modalities in Recent Aquaculture/Ocean Literature***

- **Surface Water Quality**<br />
  Task: *Monitoring*; Modality: *Tabular*; Feature: *Global surface water quality measurements*<br />
  *Primary Article/Citation:* [Karim et al. (2025)](https://www.nature.com/articles/s41597-025-04715-4)<br />
  *Open Access:* [Link](https://figshare.com/articles/dataset/A_Comprehensive_Surface_Water_Quality_Monitoring_Dataset_1940-2023_2_82Million_Record_Resource_for_Empirical_and_ML-Based_Research/27800394/2?file=50757303)

- **World Ocean Database**<br />
  Task: *Monitoring*; Modality: *Tabular*; Feature: *Large-scale oceanographic observations*<br />
  *Primary Article/Citation:* [Mishonov et al. (2025)](https://www.ncei.noaa.gov/products/world-ocean-database)<br />
  *Open Access:* <https://www.ncei.noaa.gov/products/world-ocean-database>

- **Water Quality Metrics of Pond**<br />
  Task: *Monitoring*; Modality: *Tabular*; Feature: *Sensor-based pond water monitoring*<br />
  *Primary Article/Citation:* [Islam et al. (2023)](https://www.sciencedirect.com/science/article/abs/pii/S0141933123001746)<br />
  *Open Access:* <https://www.sciencedirect.com/science/article/abs/pii/S0141933123001746>

- **DeepFish**<br />
  Task: *Segmentation*; Modality: *RGB*; Feature: *Fish instance segmentation dataset*<br />
  *Primary Article/Citation:* [Nahuel et al. (2022)](https://www.nature.com/articles/s41597-022-01416-0)<br />
  *Open Access:* <https://github.com/icclabo/DeepFishDatasetScripts>

- **Fish4Knowledge**<br />
  Task: *Tracking*; Modality: *Multi-camera*; Feature: *Large-scale reef fish video dataset*<br />
  *Primary Article/Citation:* [Fisher et al. (2016)](https://link.springer.com/book/10.1007/978-3-319-30208-9)<br />
  *Open Access:* <https://github.com/icclabo/Fish-Detection-Tracking-and-Classification>

- **FishNet**<br />
  Task: *Recognition*; Modality: *RGB*; Feature: *Fish species recognition benchmark*<br />
  *Primary Article/Citation:* [Khan et al. (2023)](https://ieeexplore.ieee.org/document/10377207)<br />
  *Open Access:* <https://github.com/icclabo/FishNet>

- **FishTrack23**<br />
  Task: *Segmentation*; Modality: *RGB*; Feature: *Underwater image segmentation benchmark*<br />
  *Primary Article/Citation:* [Dawkins et al. (2023)](https://ieeexplore.ieee.org/document/10483862)<br />
  *Open Access:* <https://github.com/icclabo/ConvertFishTrack23>

- **DIDIDSONAR**<br />
  Task: *Identification*; Modality: *Sonar*; Feature: *DIDSON sonar fish identification dataset*<br />
  *Primary Article/Citation:* [McCann et al. (2018)](https://www.nature.com/articles/sdata2018190)<br />
  *Open Access:* [Link](https://springernature.figshare.com/collections/An_Underwater_Observation_Dataset_for_Fish_Classification_and_Fishery_Ecology/4039202)

- **SOLAQUA**<br />
  Task: *Autonomous*; Modality: *Multimodal*; Feature: *Autonomous aquaculture perception dataset*<br />
  *Primary Article/Citation:* [Ohrem et al. (2025)](https://arxiv.org/abs/2504.01790)<br />
  *Open Access:* <https://data.sintef.no/feature/fe-a8f86232-5107-495e-a3dd-a86460eebef6>

- **AQUALOC**<br />
  Task: *Autonomous*; Modality: *Multimodal*; Feature: *Multimodal underwater localization dataset*<br />
  *Primary Article/Citation:* [Ferrera et al. (2019)](https://arxiv.org/abs/1910.14532)<br />
  *Open Access:* <https://www.lirmm.fr/aqualoc/>

- **FCNet**<br />
  Task: *Counting*; Modality: *RGB*; Feature: *Multi-scale fish counting dataset*<br />
  *Primary Article/Citation:* [Wang et al. (2025)](https://www.sciencedirect.com/science/article/pii/S0168169925012785)<br />
  *Open Access:* <https://github.com/icclabo/FCNet>



## Software

### Convex Tools and Solvers:
- [CVX][CVX] - A  MATLAB-based modeling system used for defining and solving disciplined convex programs (DCPs).
- [SeDuMi][SeDuMi] - A Matlab/GNU Octave package for solving convex optimization problems involving linear equations and inequalities, second-order cone constraints, and semidefinite constraints (linear matrix inequalities).
- [SDPT3][SDPT3] - A MATLAB software for semidefinite-quadratic-linear programming.
- [Gurobi][Gurobi] - A commercial mathematical optimization solver (engine) used for decision intelligence and prescriptive analytics.
- [MOSEK][MOSEK] - A specialized, high-performance software package designed for solving large-scale mathematical optimization problems.
- [GLPK][GLPK] - A GNU Linear Programming Kit is a software package intended for solving large-scale linear programming, mixed integer programming, and other related problems.

### Statistics Software:
- [wcc][wcc] - An experimental R package for conducting windowed cross-correlation analyses.
- [varde][varde] - An experimental R package for decomposing the variance in mixed effects models.
- [agreement][agreement] - An experimental R package for estimating inter-rater reliability.


### Quarto Extensions
- [lordicon][lordicon] - A stable Quarto extension for embedding animated [Lordicon](https://www.lordicon.com/icons) icons in HTML.
- [honeypot][honeypot] - An experimental Quarto extension for detecting LLM cheating on HTML assignments.
- [details][details] - A stable Quarto extension for embedding interactive details blocks in HTML documents.
- [embedpdf][embedpdf] - A stable (but questioning) Quarto extension for embedding PDF files in HTML.

### Docker Images:
- [rstudio2u][rstudio2u] - A multiarchitecture (amd64/arm64) image combining rstudio and r2u
- [rocker-bayes][rocker-bayes] - A multiarchitecture (amd64/arm64) image for Bayesian analysis in R
- [wsl-whisper][wsl-whisper] - A WSL (amd64) image for AI transcription from R with CUDA-support

[CVX]: https://cvxr.com/cvx/doc/solver.html
[SeDuMi]: https://github.com/icclabo/sedumi
[SDPT3]: https://blog.nus.edu.sg/mattohkc/softwares/sdpt3/
[Gurobi]: https://www.gurobi.com/
[MOSEK]: https://www.mosek.com/
[GLPK]: https://www.gnu.org/software/glpk/
[wcc]: https://github.com/icclabo/wcc
[varde]: https://github.com/icclabo/varde
[agreement]: https://github.com/icclabo/agreement
[lordicon]: https://github.com/icclabo/lordicon
[honeypot]: https://github.com/icclabo/honeypot
[details]: https://github.com/icclabo/details
[embedpdf]: https://github.com/icclabo/embedpdf
[rstudio2u]: https://github.com/icclabo/rstudio2u
[rocker-bayes]: https://github.com/icclabo/rocker-bayes
[wsl-whisper]: https://github.com/icclabo/wsl-whisper
[wsl-ollama]: https://github.com/icclabo/wsl-ollama
